### ISSUE TITLE
Adding z to interpolation

### ISSUE THREAD

**Issue by chromafunk** [yuki-koyama/mathtoolbox#79]
Hi, thanks for the lib ! 

I do this on python and trying to port it to C++ now: 

```
# Interpolate
rbf = scipy.interpolate.Rbf(x, y, z, function='linear')
zi = rbf(xi, yi)
```
the scipy interpolate function accepts up to four inputs for the interpolation, in my case I'm using x,y and z 
Is it possible to replicate this with `rbf_interpolator.SetData()` ? 

Thanks

**Comment by leonleon33156** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yuki-koyama** [comment]
Yes. The method `SetData()` takes `X` and `y` as inputs. The input `X` is a matrix where each column represents a data point. This can include any number of data points. This is similar to scipy https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RBFInterpolator.html .
